apiVersion: apps/v1
kind: Deployment
metadata:
  name: i23puckdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puckdbviewer
  template:
    metadata:
      labels:
        app: puckdbviewer
    spec:
      securityContext:
        runAsUser: 37693 # can run as me, need to add permissions to get it to run from yosoku namespace
        runAsGroup: 37848
        supplementalGroups:  
          - 37900
      containers:
      - name: puckdbviewer
        securityContext:
          privileged: false
        image: gcr.io/diamond-privreg/puckdb-i23/puckdb:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
          - mountPath: /dls
            name: dls
            mountPropagation: HostToContainer
      volumes:
      - name: dls
        hostPath:
          path: /dls
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: i23puckdbviewer-service
spec:
  selector:
    app: puckdbviewer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
  externalTrafficPolicy: Cluster
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: i23puckdb-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - i23puckdb.diamond.ac.uk
  rules:
  - host: i23puckdb.diamond.ac.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: i23puckdbviewer-service # this must match the name of the service you want to target
            port:
              number: 80 # or does this need to be 5000??